joak990/Chefcitoos-PF-Front

src/components/Button/index.jsx
src/components/ErrorMessage/index.jsx
src/components/Footer/index.jsx
src/components/Img/index.jsx
src/components/Input/index.jsx
src/components/Line/index.jsx
src/components/List/index.jsx
src/components/PagerIndicator/index.jsx
src/components/Radio/index.jsx
src/components/RadioGroup/index.jsx
src/components/RatingBar/index.jsx
src/components/SelectBox/index.jsx
src/components/Slider/index.jsx
src/components/Text/index.jsx
src/components/TextArea/index.jsx
src/components/index.js

Add components

---

package-lock.json
package.json
src/Redux/reducer.js
src/Redux/store.js
src/index.js

Agregando store-reducer / modificando index

Agregando store-reducer / modificando index

---

src/Redux/reducer.js
src/index.js

modificando reducer

---

src/App.jsx
src/Views/Creaciones.jsx
src/Views/FormCreate.jsx

Route create and button create

Route create and button create

---

src/Views/Creaciones.jsx

renderizado de cards en la vista Creaciones.

render_Creaciones

---

src/Views/Menu.jsx
src/components/CardMenu.jsx

se agrego adelanto menu ,responsive con cardsmenu como componente

menu con cards add

---

src/App.jsx
src/Views/Creaciones.jsx
src/Views/Publicaciones.jsx
src/components/Nav.jsx

Cree vista de Publicaciones: 
modifique el App con el Route.
modifique  el Nav.

vistaPublicaciones

---

public/index.html
src/Views/Menu.jsx
src/components/CardMenu.jsx
src/components/Modal.jsx

Add modal in menu

---

package-lock.json
package.json
src/Firebase.config.js
src/Views/Home.jsx
src/Views/Login.jsx
src/Views/Publicaciones.jsx
src/components/Nav.jsx
src/useUser.js

se agrego firebase al proyecto front , foto en home de google , local storage al recargar web , boton de logout andando

googlepopup,firebase,localstorage1

---

src/Views/Home.jsx

Agregando Diseño en la  parte inferior ("Siempre fav / creaciones mas votadas")

Agregando Diseño en la  parte inferior

---

src/Views/Menu.jsx
src/components/CardMenu.jsx

Productos renderizados en menu

Productos renderizados en menu

---

src/App.jsx
src/Views/Detail.jsx

inicio de la vista de detalles:
- modificacion en el navbar
-  modificacion en el App para agregar la ruta.

init_detail

---

src/Redux/actions.js
src/Redux/reducer.js
src/Redux/typeAction.js
src/Views/Login.jsx
src/Views/Register.jsx

register funcionando correctamente , login falta , redux allusers

register funcionando,redux,login

---

src/Views/Publicaciones.jsx
src/components/CardCreations.jsx

renderizado de cards de las creaciones en la vista de publicaciones.

renderizado_Creaciones

---

src/Redux/actions.js
src/Redux/reducer.js
src/Redux/typeAction.js
src/Views/Login.jsx
src/Views/Publicaciones.jsx
src/components/Nav.jsx

se puso localstorage en todo ui y id obtenidos , register y login funcionando con validates credentials

login terminado y register

---

src/Views/Publicaciones.jsx
src/components/CardCreations.jsx

se añadió el nombre del usuario y el nombre del producto a las cardsCreations

render_public

---

package-lock.json
package.json
src/Views/About.jsx

Actualizacion del About.
Incorporacion de los nombres de desarrolladores y  enlace a redes sociales.

About_Update

---

src/Views/Menu.jsx
src/components/CardMenu.jsx
src/components/Modal.jsx

Se realizó el diseño del modal de personalizacion

Modal personalizar

---

src/components/Modal.jsx

Diseño de modal

---

src/Redux/actions.js
src/Views/Login.jsx
src/components/Nav.jsx

validacion Login

---

src/Redux/actions.js
src/Views/Creaciones.jsx
src/Views/Home.jsx
src/Views/Login.jsx
src/Views/Register.jsx
src/components/Nav.jsx

se redirijio al menu en home todos los botones , cambios en el mobile , renderizado de texto de bienvenido con el name de la persona

cambiosmobile y actions login

---

src/components/Modal.jsx

se arreglo el bug del user , ahora el user que inicio sesion tanto de google como de mail comun que cree o compre un producto y lo guarde en creaciones esta arraigado a ese user especifico !

agregado de creacionconIDuser

---

src/Views/Creaciones.jsx

Renderiza la card de la creacion del usuario logeado

creationsReady

---

src/Redux/actions.js
src/Views/Register.jsx

register arreglado

---

src/components/Modal.jsx

Validation with errors

---

src/Views/Detail.jsx

Diseño detail

---

src/Redux/actions.js
src/Redux/reducer.js
src/Views/Creaciones.jsx
src/Views/Publicaciones.jsx
src/components/SeacrhBar.jsx

Sb publications

---

src/Redux/actions.js
src/Views/Login.jsx
src/Views/Menu.jsx
src/components/CardMenu.jsx
src/components/Modal.jsx
src/components/Nav.jsx

modo invitado y borrado logico

modo invitado y borrado logico

---

src/Views/Detail.jsx
src/Views/Login.jsx
src/Views/Register.jsx
src/components/Nav.jsx

se arrerglo bug de comentario para personas sin google , se cambio el icono del login y se agrego dos botones mobile en el menu

nuevas cosas

---

src/Views/Detail.jsx
src/components/RatingStars.jsx

comentsReady

---

src/Views/Detail.jsx

renderComponents

---

src/Views/Dashboard.jsx
src/Views/LoginAdmin.jsx

se agreago login de admins y apartado de dasboard 1 con tremor

agregado login admin y parte de dashboard

---

src/AdminUser/Products.jsx
src/AdminUser/Users.jsx

alerts de la vista de administrador solo USER/PRODUCTS

alertsAdmin

---

src/AdminUser/Products.jsx
src/AdminUser/Users.jsx

modifAlerts

---

package-lock.json
package.json
src/Views/Detail.jsx

se modifico el componente detail, para agregar un condicional y mostrar un mensaje de 'no hay comentarios' cuando la creacion no tenga comentarios aun

agregar_Mensaje_noComent

---

src/Views/About.jsx
src/components/CardMenu.jsx

add tag cardmenu

---

src/Views/Checkout.jsx
src/components/ModalShoppingCart.jsx

Se arregló la vista responsiva de la orden

Fix responsive view

---

src/Views/ResultCheckout.jsx

Add order detail in result pay

Add order detail in result pay

---

src/AdminUser/Users.jsx
src/Redux/actions.js
src/Views/Creaciones.jsx
src/Views/Detail.jsx
src/Views/Login.jsx
src/Views/Publicaciones.jsx

agregando funcionalidad de borrado logico en el dashboard y validaciones en Login

agregando funcionalidad de borrado logico

---

src/Redux/actions.js
src/Views/Home.jsx

solucionando error de action y home

solucionando error de action y home

---

src/Views/Home.jsx
src/components/Card.jsx

modificando cards por default

---

src/App.jsx
src/Views/Checkout.jsx

Guardar direccion de envio en orden

Guardar direccion de envio en orden

---

public/index.html
src/AdminUser/CreationsAdmin.jsx
src/AdminUser/Dashboard.jsx
src/Redux/actions.js
src/components/ModalComments.jsx

modificando dashboard de ordenes y comentarios de las creaciones

modificando dashboard de ordenes y comentarios de las creaciones

---

src/Views/Home.jsx
src/Views/Publicaciones.jsx
src/components/CardCreations.jsx

se añadió el average al home, creaciones, publicaciones

average home,creaciones,publicaciones

---

src/Views/UserProfile.jsx

modificacion del perfil del usuario

alerts_user_Profile

---

src/Views/UserProfile.jsx

add_reload

---

src/AdminUser/CardGridMap.jsx

arreglando error en CargGrip

---

src/Views/Detail.jsx

agregando seccion de carnes en Detail

agregando seccion de carnes

---

src/AdminUser/Chardonut.jsx
src/AdminUser/Dashboard.jsx

agregando seccion de bebidas en la dona

agregando seccion de bebidas en la dona

---

package-lock.json
package.json
public/index.html
src/AdminUser/CreationsAdmin.jsx
src/AdminUser/NavAdmin.jsx
src/AdminUser/Products.jsx
src/AdminUser/validationForm.js
src/components/ModalProducts.jsx
src/firebase-config-img.js

Guardar producto y editar producto

Guardar producto y editar producto

---

src/AdminUser/CreationsAdmin.jsx
src/AdminUser/Products.jsx
src/AdminUser/Users.jsx
src/components/ModalComments.jsx

Mejoras de css

---

src/components/ModalComments.jsx

agregando texto a Modal Comments

agregando texto a Modal Comments

---

src/AdminUser/Chardonut.jsx
src/AdminUser/Dashboard.jsx
src/Views/About.jsx
src/Views/Publicaciones.jsx

Mejoras de css y estado de orden

Mejoras de css y estado de orden
